name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  php-check:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: PHP Syntax Check
        run: |
          find plugin -name "*.php" -print0 | xargs -0 -n1 php -l