name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:

  release:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v4

      - name: Build Plugin Zip
        run: |
          mkdir build
          cp -r plugin/wp-amelia-woocommerce-cleanup build/
          cd build
          zip -r wp-amelia-woocommerce-cleanup.zip wp-amelia-woocommerce-cleanup

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/wp-amelia-woocommerce-cleanup.zip